import React from 'react';
import * as Icons from 'hugeicons-react';

interface IconProps {
    name: string;
    className?: string;
    size?: number | string;
}

const nameMap: Record<string, string> = {
    ac_unit: 'SnowflakeIcon',
    account_balance_wallet: 'Wallet01Icon',
    account_circle: 'UserCircleIcon',
    add: 'PlusSignIcon',
    add_a_photo: 'CameraAdd01Icon',
    add_circle: 'AddCircleIcon',
    analytics: 'Analytics01Icon',
    architecture: 'Building01Icon',
    arrow_back: 'ArrowLeft01Icon',
    arrow_forward: 'ArrowRight01Icon',
    arrow_forward_ios: 'ArrowRight01Icon',
    auto_awesome: 'StarIcon',
    bakery_dining: 'CroissantIcon',
    bolt: 'ZapIcon',
    calendar_month: 'Calendar01Icon',
    calendar_today: 'Calendar02Icon',
    calendar_view_month: 'Calendar01Icon',
    call: 'CallIcon',
    campaign: 'Megaphone01Icon',
    card_membership: 'MembershipIcon',
    category: 'Folder01Icon',
    check: 'Tick01Icon',
    check_circle: 'TickCircleIcon',
    chevron_left: 'ArrowLeft01Icon',
    chevron_right: 'ArrowRight01Icon',
    close: 'Cancel01Icon',
    cloud_upload: 'CloudUploadIcon',
    corporate_fare: 'Building04Icon',
    deck: 'ChairIcon',
    delete: 'Delete01Icon',
    delete_sweep: 'Delete02Icon',
    description: 'DocumentTextIcon',
    desk: 'ComputerIcon',
    diversity_3: 'UserMultipleIcon',
    domain: 'Building02Icon',
    door_front: 'Door01Icon',
    download: 'Download01Icon',
    draw: 'PencilIcon',
    east: 'ArrowRight01Icon',
    edit: 'Edit01Icon',
    edit_document: 'NoteEditIcon',
    edit_note: 'NoteEditIcon',
    error: 'Alert01Icon',
    event: 'Calendar03Icon',
    event_available: 'CalendarTick01Icon',
    event_busy: 'CalendarRemove01Icon',
    event_note: 'Note01Icon',
    expand_more: 'ArrowDown01Icon',
    filter_list: 'FilterIcon',
    fingerprint: 'FingerprintIcon',
    format_list_bulleted: 'ListIcon',
    gavel: 'GavelIcon',
    grid_view: 'GridIcon',
    group: 'UserGroupIcon',
    group_off: 'UserGroupOffIcon',
    groups: 'UserMultipleIcon',
    help_outline: 'HelpCircleIcon',
    hourglass_empty: 'HourglassIcon',
    how_to_reg: 'UserTick02Icon',
    hub: 'Share01Icon',
    id_card: 'IdCardIcon',
    image: 'ImageIcon',
    inventory_2: 'Box01Icon',
    key: 'Key01Icon',
    key_visualizer: 'Key02Icon',
    language: 'GlobeIcon',
    list_alt: 'List02Icon',
    local_cafe: 'Coffee01Icon',
    location_on: 'Location01Icon',
    lock: 'LockIcon',
    lock_reset: 'LockUnlockIcon',
    logout: 'Logout01Icon',
    loyalty: 'HeartIcon',
    mail: 'Mail01Icon',
    mark_email_read: 'MailTick01Icon',
    meeting_room: 'UserGroupIcon',
    menu: 'Menu01Icon',
    more_horiz: 'MoreHorizontalIcon',
    noise_control_on: 'SoundIcon',
    notifications: 'Notification01Icon',
    notifications_active: 'Notification02Icon',
    panel_left: 'SidebarLeftIcon',
    payments: 'Money01Icon',
    pending_actions: 'Time02Icon',
    person: 'UserIcon',
    person_add: 'UserAdd01Icon',
    person_off: 'UserRemove01Icon',
    person_search: 'UserSearch01Icon',
    photo_camera: 'Camera01Icon',
    print: 'PrinterIcon',
    priority_high: 'Alert02Icon',
    qr_code: 'QrCodeIcon',
    qr_code_2: 'QrCode02Icon',
    qr_code_scanner: 'ScanIcon',
    receipt_long: 'ReceiptIcon',
    refresh: 'RefreshIcon',
    repeat: 'RepeatIcon',
    restaurant: 'RestaurantIcon',
    rocket_launch: 'RocketIcon',
    save: 'Save01Icon',
    schedule: 'Time01Icon',
    search: 'Search01Icon',
    security: 'SecurityIcon',
    send: 'Send01Icon',
    settings: 'Settings01Icon',
    settings_input_antenna: 'AntennaIcon',
    shield: 'Shield01Icon',
    shopping_cart: 'ShoppingCart01Icon',
    storefront: 'StoreIcon',
    support_agent: 'CustomerSupportIcon',
    task_alt: 'TaskDone01Icon',
    token: 'CoinIcon',
    touch_app: 'Tap01Icon',
    trending_down: 'TrendingDown01Icon',
    trending_up: 'TrendingUp01Icon',
    tv: 'Tv01Icon',
    upload: 'Upload01Icon',
    verified: 'TickDouble01Icon',
    verified_user: 'UserTick01Icon',
    view_list: 'ListViewIcon',
    visibility: 'ViewIcon',
    visibility_off: 'ViewOffIcon',
    water_drop: 'DropletIcon',
    west: 'ArrowLeft01Icon',
    widgets: 'WidgetIcon',
    wifi: 'WifiIcon',
    wifi_off: 'WifiOffIcon',
    workspace_premium: 'Award01Icon'
};

export const Icon: React.FC<IconProps> = ({ name, className, size = 24 }) => {
    // Determine mapped name, fallback to Alert01Icon
    const hugeName = nameMap[name] || 'Alert01Icon';
    const Component = (Icons as any)[hugeName] || Icons.Alert01Icon;

    return <Component className={className} size={size} />;
};
